name: Build A90 Ransomware APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Repositoriyi Çek
      uses: actions/checkout@v4

    - name: Python Ortamını Kur
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Gerekli Paketleri Yükle
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git ccache libffi-dev libssl-dev zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses-dev libreadline-dev libsqlite3-dev tk-dev
        pip install --upgrade pip
        pip install "cython<3.0.0" buildozer

    - name: APK Derleme İşlemini Başlat
      run: |
        buildozer init
        sed -i 's/requirements = python3,kivy/requirements = python3,kivy,ffpyplayer/g' buildozer.spec
        sed -i 's/source.include_exts = py,png,jpg,kv,atlas/source.include_exts = py,png,jpg,mp3,wav/g' buildozer.spec
        sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/g' buildozer.spec
        buildozer -v android debug

    - name: APK Dosyasını Yükle
      uses: actions/upload-artifact@v4
      with:
        name: A90-Ransom-APK
        path: bin/*.apk
